### ISSUE TITLE
Mosquitto pub on docker-compose v0.4.0

### ISSUE THREAD

**Issue by danielnunesdeoliveira** [dojot/docker-compose#129]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] support request

* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
My data should be published on graph.
![image](https://user-images.githubusercontent.com/29581014/65995085-25e66300-e46b-11e9-97af-4f537d719dfe.png)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**
![image](https://user-images.githubusercontent.com/29581014/65995023-051e0d80-e46b-11e9-8074-8a691c35797b.png)

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version docker-compose.yml: 2.1
  - Docker-Compose version: v0.4.0
  - Operating system: Ubuntu 16.04 LTS

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by raulnegreiros** [comment]
Hello Daniel,
this dojot's version comes with the mqtt unsecure mode disabled by default, i. e. you can only connect to the broker using a certificate. If you want to enable the unsecure mode, please change the environment variable "ALLOW_UNSECURED_MODE" located at docket-compose.yml to true.
