### ISSUE TITLE
Last docker-compose is working(0.4.2),  but others is not working

### ISSUE THREAD

**Issue by danielnunesdeoliveira** [dojot/docker-compose#143]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] support request

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
The web interface is not available at http://localhost:8000.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
![image](https://user-images.githubusercontent.com/29581014/76802085-aef11c80-67b5-11ea-9f7a-28912e50e47e.png)

![image](https://user-images.githubusercontent.com/29581014/76802693-ff1cae80-67b6-11ea-979b-b153161a8ff6.png)

* **What is the expected behavior?**
The web interface should be available at http://localhost:8000.

* **What is the motivation / use case for changing the behavior?**
ERROR: for postgres-users  Container "a7e4bccba331" is unhealthy.

ERROR: for auth  Container "a7e4bccba331" is unhealthy.

ERROR: for kong-migration  Container "a7e4bccba331" is unhealthy.

* **Please tell us about your environment:**
  
  - Version: 0.3.1
  - Docker version: 18.03.1-ce
  - Operating system: Ubuntu 16.04 LTS 64

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by mprevide** [comment]
Hi,

Please try to change your docker-compose.yml, change the images postgres:9.4-alpine for dojot/postgres:9.4.24-alpine.

Example:

```
....
  postgres:
    image: dojot/postgres:9.4.24-alpine
...
 postgres-users:
    image: dojot/postgres:9.4.24-alpine
....
```

**Comment by danielnunesdeoliveira** [comment]
I was followed by me. Now, It is working!
