### ISSUE TITLE
(Flowbroker/GUI Notification) I wanna using channel to see my notifications

### ISSUE THREAD

**Issue by danielnunesdeoliveira** [dojot/docker-compose#144]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] support request

* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
I wanna see my notifications on GUI interface

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**
I should see all my notification in just one location.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: 0.4.2
  - Docker version: 18.03.ce
  - Operating system: Ubuntu 16.04 LTS 64

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by mprevide** [comment]
I closed this issue, because it is in the wrong repository. Please open a new issue in the dojot/dojot repository.
