### ISSUE TITLE
Cant-t instalL DOJOT. Connection Refused

### ISSUE THREAD

**Issue by RogerioCassares** [dojot/docker-compose#17]
Hello guys I am from Brazil ant when I am tryng to install dojot via docker composer I have a lot of troubles. Please, may you help me to solve them and reach the dojot to use and develop our applications, please! 

*Problem 1*: I've installed dojot in root repository /docker-compose, when I run ***sudo ./kong.config.sh*** it appears ***curl: (7) Failed to connect to localhost port 8001: Conexão recusada***

*Problem 2*: When the part above was ok, when i was running ***sudo ./create.user.sh***, there was a similar message ***curl: (7) Failed to connect to 172.18.0.2 port 5000: Conexão recusada
No JSON object could be decoded***

I've been trying to install this more then 1 month and I cant got it! :( 

May you guys could help me, please? 

Best Regards,
Rogério Cassares Pires

**Comment by mmagr** [comment]
Hello Rogério,

Thanks for trying out dojot!

We're currently doing some heavy refactoring and implementation work on some of the modules (services) that comprise dojot (authorization and authentication in particular). Since our master in this repo is configured to use the latest (sometimes not yet fully integrated) version of the services, some instability in its deployment may occur.

To try out the platform, I'd suggest you to use this repository latest tag (0.1.0-dojot). That way you should face less hurdles along the way.

To setup an environment using said release, please use the following

```shell
git clone https://github.com/dojot/docker-compose.git
# Cloning into 'docker-compose'...
# remote: Counting objects: 379, done.
# remote: Compressing objects: 100% (16/16), done.
# remote: Total 379 (delta 10), reused 15 (delta 6), pack-reused 356
# Receiving objects: 100% (379/379), 146.75 KiB | 0 bytes/s, done.
# Resolving deltas: 100% (201/201), done.
# Checking connectivity... done.
cd docker-compose/

# this switches the local copy to the stable release I mentioned.
git checkout 0.1.0-dojot
# Note: checking out '0.1.0-dojot'.
# 
# You are in 'detached HEAD' state. You can look around, make experimental
# changes and commit them, and you can discard any commits you make in this
# state without impacting any branches by performing another checkout.
# 
# If you want to create a new branch to retain commits you create, you may
# do so (now or later) by using -b with the checkout command again. Example:
# 
#   git checkout -b <new-branch-name>
# 
# HEAD is now at a9061e4... Fast-forwards components to 0.1.0-dojot-RC2

docker-compose up -d 
# Creating network "dockercompose_default" with the default driver
# Creating dockercompose_gui_1
# Creating dockercompose_mongodb_1
# Creating dockercompose_mashup_1
# Creating dockercompose_postgres_1
# Creating dockercompose_perseo-core_1
# Creating dockercompose_mqtt_1
# Creating dockercompose_coap_1
# Creating dockercompose_device-manager_1
# Creating dockercompose_sth_1
# Creating dockercompose_perseo-fe_1
# Creating dockercompose_orion_1
# Creating dockercompose_apigw_1
# Creating dockercompose_iotagent_1
# Creating dockercompose_auth_1

# now, as you might have already noticed, give the services some time to boot
# otherwise you'll get those nasty "connection refused" errors
# to be on the safe side, something around 5min should suffice
sudo ./kong.config.sh 
sudo ./create.user.sh 
# {
#     "message": "user created",
#     "user": {
#         "id": "f1b66d20-75a8-471e-b499-c84dec3e66a4",
#         "service": "admin",
#         "username": "admin"
#     }
# }
```

With that done, you should be able to use the system on http://localhost:8000

**Comment by RogerioCassares** [comment]
Hello @mmagr ! I've started a new virtual box enviormente, Ubuntu x64 16.04.03 2GB RAM 37 HD.
So I've installed docker engine CE and docker compose with the installation tested!

Now I have follow exactly the same steps you post above. So when I've run ./koong.conf.sh there was again connection failed. What should I do?

I am really interested to use dojot, but this steps break all my tries! 

![image](https://user-images.githubusercontent.com/25107890/32659886-b7c7322e-c607-11e7-9f77-3ea62955a1d1.png)



Best Regards, 

Rogério Cassares Pires

**Comment by mmagr** [comment]
Hello @RogerioCassares,

Can you please paste the results of the following here?
```shell
# those should be run for the same directory of docker-compose 
# (~/docker-compose in your case, apparently)
docker-compose images
docker-compose ps
```

Also, please notice

**Comment by RogerioCassares** [comment]
Hello Matheus, It seems something is missing at docker-compose. Please, take a look: 

![image](https://user-images.githubusercontent.com/25107890/32661428-16db7f4e-c60e-11e7-99da-47c4758cc104.png)

**Comment by mmagr** [comment]
It appears your current user isn't on `docker` group.
Running the commands with sudo should do the trick.

**Comment by RogerioCassares** [comment]
Sorry for the mistake. 

Here it is ! 

![image](https://user-images.githubusercontent.com/25107890/32662152-ac4c1262-c610-11e7-87a3-c4f99e8375df.png)

**Comment by mmagr** [comment]
... and if you try to run `sudo ./kong.config.sh` now it would fail again?
Can you please run that once more?

If it is still failing, I'd ask you to please attach the apigw's log.

To obtain it:
```shell
date > apigw.log
sudo docker-compose logs --tail 1000 apigw >> apigw.log
```

**Comment by RogerioCassares** [comment]
Hello Matheus! Suddenly it seems working. take a look! 

![image](https://user-images.githubusercontent.com/25107890/32662804-e0c94a62-c612-11e7-86b3-4a382cdac90f.png)


Great! I will post the steps on terminal and close the issue!

**Comment by wandersonsampaio** [comment]
Boa tarde Rogerio, estou instalando a versão dojot de acordo com a documentação, porém apos da o comando git, a mesma não clona o  ./kong.config.sh nem o client_user alguma dica, tentei pegar de outras versões, mas da erro na hora de rodar o kong.config,
