### ISSUE TITLE
503 status on first install

### ISSUE THREAD

**Issue by marciopamplona** [dojot/docker-compose#21]
I proceed with a clean install, with master the branch:
- ubuntu 16.04LTS 
- docker 17.09.1-ce
- docker-compose 1.18

The front page loads but dont login, i'm receiving http status 503 from /auth (service not available).

**Comment by giovannicuriel** [comment]
Hi!
Could you, please, check if all containers are up and running? It's ok if *kong-migration* and *ma_redis* are down. If any other is not running - particularly the *auth* container - could you send us the logs of all stopped ones? (``docker-compose logs auth``)

Also, did you try to use the last release (tag 0.1.0-dojot)?

**Comment by marciopamplona** [comment]
the 'auth' container is restarting continuously, the logs : 

MAIL_HOST set to NOEMAIL. This is unsafe and there's no way to reset users forgotten password
Waiting for postgres...
Postgres is ready
MAIL_HOST set to NOEMAIL. This is unsafe and there's no way to reset users forgotten password
Creating initial user and permission...
Could not connect to the database.
(postgresql.exceptions.UndefinedTableError) relation "user" does not exist
  CODE: 42P01
  LOCATION: File 'parse_relation.c', line 987, in parserOpenTable from SERVER
  POSITION: 35
STATEMENT: [parsing]
  LINE:
    FROM "user"
         ^ [line 2, character 6]
  statement_id: py:0x7fdde9de8a20
  string:
    SELECT "user".id AS user_id
    FROM "user"
    WHERE "user".username = $1
CONNECTION: [failed block]
  client_address: 172.18.0.20/32
  client_port: 33494
  version:
    PostgreSQL 9.4.15 on x86_64-unknown-linux-gnu, compiled by gcc (Debian 4.9.2-10) 4.9.2, 64-bit
CONNECTOR: [Host] pq://kong@postgres:5432
  category: None
DRIVER: postgresql.driver.pq3.Driver [SQL: 'SELECT "user".id AS user_id \nFROM "user" \nWHERE "user".username = %(username_1)s'] [parameters: {'username_1': 'admin'}]

**Comment by alexandre-vasc** [comment]
Auth should have created the database tables on first startup. Looks like something went wrong.
Maybe restart auth solve the problem:

docker-compose restart auth

Could you try the command and say if its worked?

**Comment by mmagr** [comment]
Marcelo, acho que você deve estar caindo no problema tratado pelo dojot/auth#19
Dito isso, eu pediria para você tentar fazer um pull da versão mais nova do serviço (o PR foi mergeado ontem), mas a compilação automática da imagem falhou (dojot/auth#23 e dojot/auth#24).

Caso queira usar as versões mais novas, minha sugestão seria que vc baixasse o branch do dojot/auth#24, e gerasse a imagem localmente.

Dito isso - também aproveito a oportunidade para lembrá-lo de que o master desse repositório usa versões ainda não validadas dos serviços, então provavelmente você vai acabar trombando em outros percalços. Minha sugestão é usar o branch 0.1.x mesmo (contém as tags das RCs e das versões estáveis).

**Comment by mmagr** [comment]
Marcio, os PRs relevantes foram aprovados, e o build automático rodou.

Por favor, você poderia atualizar a sua imagem do auth e verificar se o problema foi resolvido?

Para atualizar o auth:

```shell
docker-compose stop
docker-compose pull auth
docker-compose up -d --build
```
Todos os comandos acima podem precisar de sudo (dependendo se o seu usuário está no grupo docker ou não, e devem ser executados na raíz da instalação do docker-compose.

**Comment by marciopamplona** [comment]
Feito! up and runnning!

Thanks!
