### ISSUE TITLE
Any plans for Raspberry Pi?

### ISSUE THREAD

**Issue by mllima** [dojot/docker-compose#59]
Are there plans to make it available for Raspberry Pi?
Trying at Raspberry Pi 3 gives the following result:

pi@raspberrypi:~ $ cd docker-compose/
pi@raspberrypi:~/docker-compose $ sudo docker-compose up -d
Pulling zookeeper (zookeeper:3.4)...
3.4: Pulling from library/zookeeper
ERROR: no matching manifest for linux/arm in the manifest list entries
pi@raspberrypi:~/docker-compose $

**Comment by rascaraficci** [comment]
dojot was conceived to run on private and public clouds. It would be necessary to make it lighter to run on edge devices such as Raspberry Pi.
