### ISSUE TITLE
Open the web interface

### ISSUE THREAD

**Issue by victordamazio** [dojot/docker-compose#63]
I think it's a simple request but I'm having trouble.

I'm following the tutorial right here:

http://dojotdocs-ptbr.readthedocs.io/pt_BR/latest/installation-guide.html

I just typed in the terminal:

`docker-compose up -d`

Now I'm trying to open the web interface, but I can't.

I tried 

`http://localhost:8000`

But it didn't work.

I also tried:

`http://192.168.99.100:8000/`

And it showed the message:

`{"message":"no API found with those values"}`

Am I going into the right direction? What should I do now?

**Comment by giovannicuriel** [comment]
Hi!

Is this still happening? This might occur while bringing up all services - it might take a while after all docker containers are running to web interface become available. But this error should disappear after a minute or so - specially if this is the first time you start all containers.

Also, could you check if "kong-config" container executed correctly? This container should start, apply a few configurations to apigw and exit - it's expected that if you execute ```docker-compose ps``` its state is ```Exit 0```. Could you send its logs? (by executing ```docker-compose logs kong-config```)

**Comment by victordamazio** [comment]
Well, maybe the problem is with kong-config.

I clicked the file in my folder, then it says:

`curl: (6) Couldn't resolve host 'apigw'`

What should I do now?

**Comment by victordamazio** [comment]
Also, I tried executing `docker-compose logs kong-config`, but the response was `Couldn't connect to Docker daemon - you might need to run `docker-machine start default``.

**Comment by giovannicuriel** [comment]
Some systems do need a "docker-machine" running in order to use containers. You might need to execute the suggested ```docker-machine start default```and a ```eval $(docker-machine env)``` before calling ```docker-compose up -d``` (or any docker-related command for that matter). I think that it this docker-machine is not automatically started when you reboot your computer.

The script you executed is actually ran by ```kong-config``` container. It will register all APIs in Kong so that you can access them by sending requests to it.

**Comment by victordamazio** [comment]
No need for help anymore, solved the problem.

I just needed to try it on Ubuntu, I was trying to use Windows, it was so easy to solve this problem.

**Comment by victordamazio** [comment]
Yes
