### ISSUE TITLE
Can't send a message to Web Interface

### ISSUE THREAD

**Issue by victordamazio** [dojot/docker-compose#64]
Yesterday, everything was working fine, but then I tried the same command, and it didn't work.

The command is the same from the tutorial:

`mosquitto_pub -t /devices/thermometers -i "admin:c800df" -m '{"temperatura" : 60}'`

The `temperatura` instead of `temperature` is not a typo.

**Comment by victordamazio** [comment]
![image](https://user-images.githubusercontent.com/25162231/43144329-3d699954-8f33-11e8-810a-3bd9babb7e2d.png)

**Comment by giovannicuriel** [comment]
I suspect that the problem is that the message was not received right? Could you, please, check if all containers are ok? (executing the command `docker-compose ps`. It is expected that both `kong-config` and `kong-migration` are down.

**Comment by victordamazio** [comment]
When I type `docker-compose ps`, the `iotagent-mqtt` is on `Exit 255`

I executed `docker-compose logs -f iotagent-mqtt` but I don't know what happened, and I don't think nothing changed, the messages are still not working.

**Comment by victordamazio** [comment]
Guess it didn't work, maybe tomorrow I'll try reinstalling everything.

**Comment by giovannicuriel** [comment]
All containers are stopped? Or is it just iotagent-mqtt?

**Comment by victordamazio** [comment]
The kong containers and iotagent are down.

I'll try messing with it again, but guess I'll try uninstalling everything, but it will probably not work, the issue will likely come back when I turn off the Virtual Machine once again.

**Comment by victordamazio** [comment]
`Starting dockercompose_iotagent-mqtt_1 ... error`

**Comment by victordamazio** [comment]
I tried typing `sudo docker-compose up` and it showed:

https://gamefaqs.gamespot.com/boards/234547-super-smash-bros-ultimate/76514442

**Comment by victordamazio** [comment]
I'm typing this command, according to the tutorial:

`mosquitto_pub -t /device/thermometers -i "admin:5aded0" -m '{"temperature" : 60}'`

Do you think there's any mistake in this? Any typo?

**Comment by victordamazio** [comment]
Also, I tried `sudo docker-compose up -d`

```
dockercompose_ejbca_1 is up-to-date
dockercompose_data-broker-redis_1 is up-to-date
dockercompose_postgres_1 is up-to-date
dockercompose_gui_1 is up-to-date
dockercompose_mongodb_1 is up-to-date
dockercompose_mosca-redis_1 is up-to-date
dockercompose_zookeeper_1 is up-to-date
dockercompose_auth-redis_1 is up-to-date
dockercompose_rabbitmq_1 is up-to-date
dockercompose_device-manager-redis_1 is up-to-date
Starting dockercompose_kong-migration_1 ... 
dockercompose_auth_1 is up-to-date
Starting dockercompose_kong-migration_1
dockercompose_history_1 is up-to-date
dockercompose_kafka_1 is up-to-date
dockercompose_flowbroker_1 is up-to-date
dockercompose_data-broker_1 is up-to-date
dockercompose_device-manager_1 is up-to-date
Starting dockercompose_iotagent-mqtt_1 ... 
dockercompose_persister_1 is up-to-date
Starting dockercompose_iotagent-mqtt_1 ... error

ERROR: for dockercompose_iotagent-mqtt_1  Cannot start service iotagent-mqtt: driver failed programming external connectivity on endpoint dockercompose_iotagent-mqtt_1 (825a4565cd08bd497c4596fdbacbad30Starting dockercompose_kong-migration_1 ... done
dockercompose_apigw_1 is up-to-date
Starting dockercompose_kong-config_1 ... 
Starting dockercompose_kong-config_1 ... done

ERROR: for iotagent-mqtt  Cannot start service iotagent-mqtt: driver failed programming external connectivity on endpoint dockercompose_iotagent-mqtt_1 (825a4565cd08bd497c4596fdbacbad300ab63c9844a7eb4260f9e250dcfd9b65): Error starting userland proxy: listen tcp 0.0.0.0:1883: bind: address already in use
ERROR: Encountered errors while bringing up the project.
```

Maybe this is the issue, but what should I do?

**Comment by giovannicuriel** [comment]
This might be related to docker itself, not iotagent: https://stackoverflow.com/questions/39508018/docker-driver-failed-programming-external-connectivity-on-endpoint-webserver.

Let's keep track of this issue to see if there's any update on this.

**Comment by danielnunesdeoliveira** [comment]
Hello!

I got the same problem. Can someone help me? 

**Figura 1** - Container with problem
![image](https://user-images.githubusercontent.com/29581014/153492164-edca7c0a-f0d2-44ea-89fa-a4abe00454c1.png)

The command "service docker restart" was applied by someone ? If yes, it was enough ?

**Figura 2** -  "service docker restart" command
![image](https://user-images.githubusercontent.com/29581014/153492498-6737a827-3023-436d-8b72-c2db9230d9f3.png)

I am really worried... if I kill **iotagent mqtt** container, the DEVICE_ID number can stop working? 


**Figura 3** - My device id number
![image](https://user-images.githubusercontent.com/29581014/153493366-d7453e2e-2f92-499b-815f-e3fc306d185a.png)

**Comment by danielnunesdeoliveira** [comment]
My problem was resolved.

The problem were two brokers(**iotagent-Mqtt and Mosquitto Server**) running on same port 1883.

Regards Dojot team.
