### ISSUE TITLE
Send two attributes in a message

### ISSUE THREAD

**Issue by victordamazio** [dojot/docker-compose#65]
I'm trying to make a flow work, and I am typing these two messages:

`mosquitto_pub -t /devices/geoonibus -i "admin:d34712" -m '{"Pass" : "45"}'`

`mosquitto_pub -t /devices/geoonibus -i "admin:d34712" -m '{"Local" : "-23.5505, -46.6333"}'`

Is there any way to send these two attributes together in the same message? It's a simple issue.

**Comment by giovannicuriel** [comment]
Hi!

Yes, this is indeed simple. Just send the message with both attributes set:
```bash
mosquitto_pub -t /devices/geoonibus -i "admin:d34712" -m '{"Local" : "-23.5505, -46.6333", "Pass" : "45"}
```

**Comment by giovannicuriel** [comment]
Did it work?
