### ISSUE TITLE
Bar Graphs instead of Line Graphs

### ISSUE THREAD

**Issue by victordamazio** [dojot/docker-compose#78]
Can the web interface use those? Can I replace the line graphs with the bar graphs?

**Comment by rascaraficci** [comment]
It would be necessary to change the GUI's code. In the current version, an attribute of numeric type is only shown as a line chart. 

You could associate a metadata with the attribute to indicate how it should be shown and changes the GUI code to handle it.

**Comment by victordamazio** [comment]
Can I ask for a update for Dojot to add more chart types? Not only bars, but also pies?

Is it that hard to change the GUI's Code?

**Comment by rascaraficci** [comment]
At the moment, we don't have plans to change the GUI to support different types of charts, but if you were interested in helping us to extend dojot with this feature, we can support you.

**Comment by rascaraficci** [comment]
This issue will be closed due to inactivity
