### ISSUE TITLE
Instalação e uso do Dojot

### ISSUE THREAD

**Issue by marcotchella** [dojot/docker-compose#8]
Olá
Estou fazendo testes com o Dojot e estou com um problema de funcionamento que descrevo a seguir.
Ambiente de testes:
- Maquina Virtual com Virtualbox tendo como hospedeiro o Windows 10
   Configuração de rede em Ponte de forma que o ip da maquina virtual é visto pelas maquinas da rede.
- Feita instalação a partir das instruções do docker-compose

Testes  com a instalação:
Acessei a pagina de administração, fiz o login e criei um dispositivo conforme tutoriais do canal do Youtube. 
Criei um cliente em nodejs para publicar no tópico e eis o que obtive:
- O cliente conecta e publica no tópico, porém não é recebido no painel, o mesmo fica sempre  como disabled.
- Para teste criei outro cliente que faz a subscrição no tópico e ele recebe as mensagens. Me parece que o broker Mosquitto está funcionando sem problemas.

Estou parado nesse ponto, já conferi e reconferi várias vezes e não consigo resolver.
Gostaria de contar com o auxilio pois gostaria de utilizar na minha pesquisa e prestigiar essa iniciativa nacional. 
Gostei muito da integração com o Node-Red.
Parabens pelo projeto

**Comment by giovannicuriel** [comment]
Boa tarde, @marcotchella!

Gostaria de confirmar apenas duas coisas: uma é o tópico usado para publicar as mensagens, que deve ser no formato `/<service>/<device-id>/attrs`. Se você estiver usando o script createUser.sh do repositório, o `service` vai ser "admin". O identificador do dispositivo pode ser visto na interface web.

A segunda é o formato da mensagem, que deve ser como:
`{
    "attribute1" : "valor-1",
    "attribute2" : "valor-2"
}`


(As aspas são importantes  )

Você poderia checar estes dois pontos, por favor?

Estamos trabalhando para flexibilizar tanto o tópico quanto o formato da mensagem.

**Comment by marcotchella** [comment]
Boa tarde @giovannicuriel 
 Chequei e havia um erro na montagem do tópico, faltava uma barra no inicio. A linha correta ficou no meu código em nodejs assim:
client.publish("/admin/9a1d/attrs", '{"atributo": 50 }'); 

Resolvido. Continuarei explorando e acompanhando a evolução da ferramenta.
Obrigado pelo auxílio.
