### ISSUE TITLE
postgres-users keeps restarting

### ISSUE THREAD

**Issue by giovannicuriel** [dojot/docker-compose#80]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
Container "postgres-users" keeps restarting if 'kong' user is already created in postgres.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Use an external volume for posgres. Start all containers (`docker-compose up -d`), bring them down (`docker-compose down`) and then start them again (`docker-compose up -d`).

* **What is the expected behavior?**
Container should detect that the user is already created and then exit cleanly.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: 0.2.x
  - Docker version: 
  - Operating system: [Ubuntu 16.04, Fedora 28, Ubuntu on VirtualBox (Windows 10), etc.]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

This is related to dojot/dojot#694

**Comment by danielnunesdeoliveira** [comment]
Hi @giovannicuriel 

What should I do to fix this "postgres-users" problem? Now, I can not send mqtt message.

![problema](https://user-images.githubusercontent.com/29581014/52278046-375b8780-293d-11e9-9238-374f68d4afa8.PNG)

![problema2](https://user-images.githubusercontent.com/29581014/52278059-3f1b2c00-293d-11e9-81f0-d3f6c2e32bc5.PNG)

![problema3](https://user-images.githubusercontent.com/29581014/52285510-9d500b00-294d-11e9-9d38-3e71bfee5c05.PNG)

**Comment by rascaraficci** [comment]
This has been fixed in pull request #82
