### ISSUE TITLE
Message: "Invalid endpoint requested" on History

### ISSUE THREAD

**Issue by davicedraz** [dojot/docker-compose#92]
In the [docs](https://dojot.github.io/history/apiary_v1.0.0.html), the path informed that will retrieve all data from all device’s attributes, unless a parameter is given is: 

> http://localhost:8000/device/{device_id}/history

But actually, this always returns 

```JSON
{ "msg": "Invalid endpoint requested" }
```

In order to retrieve all data from all device’s attributes, the correct path is:

> http://localhost:8000/history/device/{device_id}/history 

A quick fix on the endpoint path or in the docs can close this.

**Comment by giovannicuriel** [comment]
Hi! 
In fact we have a little ['translation table'](https://dojotdocs.readthedocs.io/en/stable/components-and-apis.html#id4) for that, along with a quick explanation of the reasons the service API is different than the one exposed in Kong

The history one is missing, though. I'll add it and change the table a bit to better explain that.

**Comment by rascaraficci** [comment]
This issue will be closed due to lack of activity for more than two months.
